### ISSUE TITLE
关于使用 Dockerfile 进行容器创建，apk 安装的 gcc 显示安装成功但进入容器后无法使用的问题

### ISSUE THREAD

**Issue by fgazer94** [kentio/ondjblog#6]
您好！我尝试使用 enkito/ondjblog:latest 内 DjangoBlog 目录下的 Dockerfile 来进行容器重建，但是重建过程中，发现虽然在 build 中显示的安装成功，但是实际安装是失败的，进入容器后，输入诸如 gcc 命令无法生效，重新执行 apk 命令后，gcc 才能生效，然后才能顺利安装成功 mysqlclient，请问您是否遇到过这种问题？您是如何解决的？

**Comment by chasenio** [comment]
嗯, 我遇到过这个情况, 在这里我陷入了一个死循环, 如果 mysqlclient 安装成功的话, 会陷入另一个问题,  启动的时候django会提示mysqlclient的版本问题, 这里我不想耗太多的时间,我选择给django降级,然后使用 pymsql
```
ImproperlyConfigured: mysqlclient 1.3.7 or newer is required; you have 0.7.6
```
------
关于 gcc 的问题

- https://github.com/kentio/DjangoBlog/blob/d961b075359525a35de03d9706a06f8402cc7e81/Dockerfile#L17
- https://github.com/kentio/DjangoBlog/blob/d961b075359525a35de03d9706a06f8402cc7e81/Dockerfile#L36

可以看到`line17`是以`--virtual`的方式安装的gcc执行依赖, 到 `line36`这些依赖全部删除了, 目的是减少image的大小,其实有相当一部分依赖只是在build阶段使用到gcc这些,  如果您要在自己image里面使用的话, `apk add --no-cache gcc` 即可.


另外: 
- 关于`--virtual` 的作用可以看[这里](https://www.cnblogs.com/sunsky303/p/11548343.html) 坑四部分
- 使用的[Dockerfile](https://github.com/kentio/DjangoBlog/blob/d961b075359525a35de03d9706a06f8402cc7e81/Dockerfile)

**Comment by fgazer94** [comment]
非常感谢！这对我很有帮助！

**Comment by chasenio** [comment]
荣幸之至.
